import openai

# Your OpenAI API key (keep this a secret!)
api_key = "YOUR-OPENAI-API-KEY"

def query_gpt(question, model="text-davinci-003"):
    """
    Asks a question to the specified GPT-3 model and returns the response.

    Args:
    - question (str): The question or prompt to send to GPT-3.
    - model (str): The model ID to use (default is DaVinci, the most capable model).

    Returns:
    - str: The text generated by GPT-3 in response to the question.
    """
    # Authenticate with the API
    openai.api_key = ""

    try:
        # Make a request to the API
        response = openai.Completion.create(
          engine=model,
          prompt=question,  # your question or prompt
          max_tokens=300  # controls the maximum length of the response
        )

        # Extract the text from the GPT-3 response
        gpt3_response = response.choices[0].text.strip()

        return gpt3_response

    except Exception as e:
        print(f"An error occurred: {e}")
        return None

# Test the function with a question or prompt
response = query_gpt("What are the health benefits of daily exercise?")
print(response)
